# Generated by Django 5.0.4 on 2024-06-14 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('d422b10a-c6fc-4779-a9cb-0d23e9ed6bb8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
