# Generated by Django 5.0.4 on 2024-06-14 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0002_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('673de2af-b3a1-4824-a1d7-2e4145f7d066'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
