# Generated by Django 5.0.4 on 2024-06-19 02:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0003_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountuser',
            options={'ordering': ('account_user_related_user',)},
        ),
        migrations.RenameField(
            model_name='accountuser',
            old_name='account_user_fulLname',
            new_name='account_user_fullname',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('0b679921-b47a-4a1c-bc40-1703583ff9a0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_related_user',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_student_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account_user_id', 'account_user_related_user'], name='will_accoun_account_e4cc70_idx'),
        ),
    ]
