# Generated by Django 5.0.4 on 2024-06-19 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0004_alter_accountuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('896cc137-338d-42dc-bfa8-da4f14c325bd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
