# Generated by Django 5.0.4 on 2024-06-19 02:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0005_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('90d96442-70d5-48a5-b37a-0d7f0f98e699'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
