# Generated by Django 5.0.4 on 2024-06-25 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('account_user_id', models.UUIDField(default=uuid.UUID('2f90c5cd-8a7b-417a-8459-26ed7a4c6677'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_user_related_user', models.CharField(editable=False, max_length=255)),
                ('account_user_fullname', models.CharField(editable=False, max_length=255)),
                ('account_user_student_number', models.CharField(max_length=20)),
                ('account_user_created_by', models.CharField(max_length=255)),
                ('account_user_created_date', models.DateTimeField(auto_now_add=True)),
                ('account_user_updated_by', models.CharField(max_length=255, null=True)),
                ('account_user_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('account_user_related_user',),
                'indexes': [models.Index(fields=['account_user_id', 'account_user_related_user'], name='will_accoun_account_e4cc70_idx')],
            },
        ),
    ]
