# Generated by Django 5.0.4 on 2024-06-25 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('d8c184fe-e0c7-450f-a351-66eefc9ff6a1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
